chore: update readme with sql admin and client role details
GoogleCloudPlatform/cloud-sql-go-connector pull request #147
Opened 2022-03-17 17:11 UTC by jackwotherspoon

Adding extra details to README.

2022-03-17 17:15 UTC, enocom requested changes

2022-03-17 17:15 UTC, enocom commented on README.md
> +[client-role]: https://console.cloud.google.com/iam-admin/roles/details/roles%3Ccloudsql.client
This is probably the link to use: https://cloud.google.com/sql/docs/mysql/roles-and-permissions.

2022-03-17 17:23 UTC, kurtisvg commented on README.md
> +
Can we figure out how to work this higher? Essentially we want to lead with "You must have a IAM member with this role" then say "here's how we figure out which IAM member we use".

2022-03-17 18:26 UTC, enocom commented on README.md
> +resolving credentials from an IAM Principal. Please see the
```suggestion
resolving credentials. Please see the
```

2022-03-30 15:38 UTC, kurtisvg approved these changes

2022-03-30 15:38 UTC, kurtisvg commented on README.md
> +[Cloud SQL Client][client-role] role. This IAM Principal will be used for
This should be "[Cloud SQL Client][client-role] role or equivalent".

2022-03-30 15:40 UTC, enocom commented on README.md
> +- IAM Principal (user, service account, etc.) with the
That seems to be how it's used here: https://cloud.google.com/iam/docs/overview.

2022-03-30 16:02 UTC, merged