chore: parse connection name before locking + cleanup
GoogleCloudPlatform/cloud-sql-go-connector pull request #500
Opened 2023-03-27 18:06 UTC by enocom

2023-03-27 18:58 UTC, jackwotherspoon requested changes

2023-03-27 18:58 UTC, jackwotherspoon commented on internal/cloudsql/instance.go
> +			// valid are surprised. We should try to surface
silly silly
```suggestion
			// valid are suppressed. We should try to surface
```

2023-03-28 17:55 UTC, enocom commented on internal/cloudsql/instance.go
> +			// valid are surprised. We should try to surface
Fixed.

2023-03-28 18:01 UTC, jackwotherspoon approved these changes

2023-03-28 18:02 UTC, merged